version: '3'
services:
  # Web Server 1 : Apache
  apache:
    image: httpd:alpine
    container_name: apache
    ports:
      - "8081:80"
    networks:
      - webnet
    volumes:
      - ./apache:/usr/local/apache2/htdocs/

  # Web Server 2 : Jetty
  jetty:
    image: jetty:9.4-jre8
    container_name: jetty
    ports:
      - "8082:8080"
    networks:
      - webnet
    volumes:
      - ./jetty:/var/lib/jetty/webapps/root

  # Nginx Reverse Proxy
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      - webnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  webnet:
